version: "3.1"
recipe: default.v1
language: sw
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
  - name: DIETClassifier
    epochs: 30
    constrain_similarities: true
  - name: EntitySynonymMapper
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 30
    constrain_similarities: true  # Add this
assistant_id: 20250618-154718-quiet-debit