FROM rasa/rasa-sdk:3.6.0
WORKDIR /app
COPY actions /app/actions
COPY requirements.actions.txt /app/requirements.txt
USER root
RUN pip install --no-cache-dir -r requirements.txt
USER 1001
ENV PATH="/opt/venv/bin:$PATH"
EXPOSE $PORT
CMD ["rasa-sdk", "--actions", "actions", "--port", "$PORT"]
