FROM rasa/rasa-sdk:3.6.0
WORKDIR /app
COPY actions /app/actions
COPY requirements.actions.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE $PORT
CMD ["start", "--actions", "actions", "--port", "$PORT"]
