FROM rasa/rasa-sdk:3.6.0
WORKDIR /app
COPY actions /app/actions
COPY requirements.actions.txt /app/requirements.txt
RUN pip install --no-cache-dir --user -r requirements.txt
EXPOSE $PORT
CMD ["rasa-sdk", "--actions", "actions", "--port", "$PORT"]
